version: "3"

services:
  crazyict-ktor-demo-api:
    container_name: crazyict-ktor-demo-api
    build: .
    ports:
      - 8080:8080
    links:
      - db

  db:
    container_name: crazyict-ktor-demo-db
    image: mysql:5.7
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DATABASE: "crazyict_ktor_demo"
#    ports:
#      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
